spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/pet_care
    username: root
    password: giabao123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
server:
  port: 8888
  servlet:
    context-path: /pet-care