spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pet_care
    username: root
    password: giabao123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: giabao7112004@gmail.com
    password: gisb quje jpua taef
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "http://localhost:5173/auth/google/callback"
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

server:
  port: 8888
  servlet:
    context-path: /pet-care

jwt:
  secretKey: Ckj2tdZqqx4zYqn0iSB9bUPIsckWdFoa/YIi1kzGWKc9qM5XCbRoPHmWhft9pZZCGeKYcAhgILzOu++4toDC0Gn9iDWTlRAlnQ8efRnVU8I=
  valid-time-duration: 60000
  refresh-time-duration: 120000
frontend:
  base:
    url: http://localhost:3000
admin:
  email: giabao7112004@gmail.com
  password: admin
  firstName: admin